### ISSUE TITLE
Wording: Which country is not a basin country?

### ISSUE THREAD

**Issue by heyarne** [q-wiki/q-wiki-server#66]
As @davidmllr suggested, we should use another description for the following questions…

- Which country is no basin country of the Baltic Sea?
- Which country is no basin country of the Caribbean Sea?
- Which country is no basin country of the Mediterranean Sea?
- Which country is not a basin country of the Baltic Sea?
- Which country is not a basin country of the Caribbean Sea?
- Which country is not a basin country of the Mediterranean Sea?

Ideas:
- Which country does not have a coast at…
- Which country is not adjacent to…
- Which country is not bordering to…
- Which country does not touch…

Votes welcome!

**Comment by davidmllr** [comment]
How about 'Which country does not border the...'?
