### ISSUE TITLE
CORS headers are missing

### ISSUE THREAD

**Issue by heyarne** [q-wiki/q-wiki-server#89]
Please add a wildcard CORS-header to https://wikidatagame-testing.azurewebservices.net to make the API usable from other websites. Example of missing header: https://wikidatagame-testing.azurewebsites.net/api/Platform/Minigame/b957e313-385a-49d1-1d85-08d796c3149c

**Comment by maltegoetz** [comment]
That makes sense, I can add that in code. Only question: Is a wildcard header a good idea here? Why not just adding q-wiki.github.io to the allowed origins?

**Comment by heyarne** [comment]
You'd need to add localhost as well in order to avoid problems while developing. In general it's common practice to just allow wildcards with APIs. After all you often want people to be able to use them everywhere.

**Comment by maltegoetz** [comment]
solved with b27c8811f97d806e936b86d44f3ab554a7c4d854
